PlaceOS/drivers

- docs/setup.md
without `shards install`:
```
$ crystal run ./src/app.cr 
Error in src/app.cr:2: while requiring "./config"
require "./config"
^
in src/config.cr:2: can't find file 'action-controller'
If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?
require "action-controller"
^
```
> readme: add shards install

- docker-compose.yml
Maps in the shards from the host as a volume. This enables adding to,
updating or otherwise changing dependancies during dev without forcing a
rebuild of the docker image.
> feat: use lib from host in docker-env

- drivers/place/smtp.cr
- drivers/place/smtp_spec.cr
- shard.lock
- shard.yml
An  SMTP driver using [crystal-email](https://github.com/arcage/crystal-email).
The SMTP client isn't neatly tested, we could use a [dummy SMTP server](https://github.com/russolsen/cr_fake_smtp).
> feat(place:smtp): smtp driver

- docs/writing-a-driver.md
Quick notes on what interfaces are and how they are used. Will expand with some more examples and context when porting across to docs site.
> docs: add notes on interface usage

- drivers/place/area_config.cr
support
"areas": [
{
...
"properties": {
"label_location": {
"x": 0.5089,
"y": 0.6673
}
}
> fix(place/area/config): allow zone.metadata.area.properties.Hash

- drivers/extron/matrix.cr
- drivers/extron/sis.cr
- drivers/extron/sis/response.cr
Resolves type issues and a missing response parser within the Extron Matrix driver.
The branch state in the originally merged PR was missing these. Due to the current lack of automated testing during merges, this would not have been caught.
> fix: Extron matrix driver

- docs/writing-a-spec.md
- drivers/vergesense/models.cr
- drivers/vergesense/vergesense_api.cr
- drivers/vergesense/vergesense_api_spec.cr
Ref: #70
Notes:
Performs initial sync on load by hitting 3 different endpoints to get complete data.
* Buildings - https://vergesense.readme.io/reference#buildings
* Floors - https://vergesense.readme.io/reference#buildings-2
* Spaces -https://vergesense.readme.io/reference#spaces-1
Individual floor information is saved in the driver state as json string, under `"#{building_ref_id}-#{floor_ref_id}"` key.
Provides `space_report_api` method to be setup as trigger to receive webhook calls.
@stakach Please take a look and let me know if something is missing or needs updating. 
PS: I haven't added sensor information to Space, did we need that?
> Vergesense Driver

- drivers/biamp/nexia.cr
- drivers/biamp/nexia_spec.cr
- drivers/biamp/tesira.cr
- drivers/biamp/tesira_spec.cr
Has drivers for:
* Tesira
* Nexia
Few notes on Tesira implementation. 
In the ruby version https://github.com/acaprojects/ruby-engine-drivers/blob/beta/modules/biamp/tesira.rb#L233, we rely on `command` parameter in `received` method to figure out the correct status to set. In crystal version of `received` method we don't have `command`.
So to work around that issue we have opted to `send` without queueing and change status rightaway: https://github.com/PlaceOS/drivers/compare/master...websymphony:aca_111_biamp_drivers?expand=1#diff-dd0234e1626a32d2221be3e61d7ebb54c50b558a12dbc9eabbe65fdf5ceb4bffR109
> Biamp drivers

- docker-compose.yml
Use of the `container_name` key is not necessary here, and may lead to container name conflicts.
> build(docker-compose): remove the container_name key for redis

- drivers/sony/projector/serial_control.cr
Adds named arguments to `to_s` invocation on the checksum. This driver previously failed to compile.
> fix(sony/projector): fix bug in rendering bytes

- shard.lock
fix event.sensitivity and fetch events limited to 10
https://github.com/PlaceOS/calendar/commit/ab8babafca01954545694da5cc116108a7af4eb3
https://github.com/PlaceOS/office365/pull/17
1. Will this cause incompatibility issues with existing PlaceOS instances that did not start off on crystal v1.0.0.?
2. Will I need to run this migration? https://github.com/PlaceOS/models/issues/75
> chore(shard.lock): bump calendar and office365

- drivers/lenel/open_access/client.cr
- shard.lock
- shard.yml
Re-adds a [dependency that was dropped](https://github.com/PlaceOS/drivers/commit/162631230c365b40c9ed40b3d46ce1b523196f33#diff-cbaa8062ee0fcfb5af8adfd98f69af4766b9ad5bb5e79158abe8da34f6fd7de0L64-L66).
Reverts semantically important changes introduced in #149.
Resolves #151.
> Resolve Lenel Open Access driver build issues

- drivers/global_cache/gc_100.cr
- drivers/global_cache/gc_100_spec.cr
- shard.lock
Adds `PlaceOS::Driver:Interface::ElectricalRelay`  to the global cache driver
> feat(global_cache): conform to electrical relay interface

- drivers/place/smtp.cr
Ideally it would have been better to add a setting called `setting?(OpenSSL::SSL::VerifyMode, :ssl_verify_mode)` so we could specify other enums/values of `OpenSSL::SSL::VerifyMode` instead of `setting?(Bool, :ssl_verify_ignore)` but that doesn't work because of this issue https://github.com/crystal-lang/crystal/pull/7382
> feat(smtp): add setting to ignore cert validation

- drivers/place/visitor_mailer.cr
Staff-api event/checkin request will [now support](https://github.com/place-labs/staff-api/commit/0794fd08336746a36e1e78f05e575dff34345f84) a new optional `host_mailbox` param, which must be used when the EVENT ID supplied is the HOST mailbox event ID instead of the room mailbox event id. This is the case for the QR code that this driver generates.
So apps (frontends) that use the QR code generated by this driver will also need a small change to read and use the 4th comma seperated data item in the qr code, and include it in checkin POSTs as a new param`host_mailbox=_`
> feat(place/visitor_mailer): add host mailbox to QR data

- drivers/lenel/open_access/client.cr
Resolves a breaking API change / layout change in upstream dep.
Introduced in d2fc0cccce54d4611ec68db7e8f9600aa8600202.
> Fix broken require from `inactive-support`

- shard.lock
Bump driver to fix a few failing compilations
> chore(shard.lock): bump driver

- drivers/vergesense/models.cr
- drivers/vergesense/vergesense_api_spec.cr
Space.People.coordinates is an array of arrays of Float (2 deep not 3), as per https://vergesense.readme.io/reference/events:
```
type SpaceReportEvent = {
...
people: {
// array of arrays of [x,y] coordinate pairs for each person detected by a device
coordinates: [Array<[Number, Number]>?],
```
> fix(vergesense): Type of Space.People.coordinates

- drivers/vergesense/models.cr
- drivers/vergesense/vergesense_api_spec.cr
a vergesense api response has been seen with `space.space_ref_id: null`, so we'll need to handle it.
The values appear to be human made strings (friendly names) not guids.
Will an additional change be needed in order to ensure `update_floor_space` func still works when space_ref_id is null?
https://github.com/PlaceOS/drivers/blob/master/drivers/vergesense/vergesense_api.cr#L122
`floor_space = floor.spaces.find { |space| space.space_ref_id == remote_space.space_ref_id }`
> Vergesense: space_ref_id can be null

- drivers/place/meet.cr
- drivers/place/meet_spec.cr
- drivers/place/router.cr
- drivers/place/router/signal_graph/node.cr
- drivers/place/router_spec.cr
Added:
- **(breaking)** `PlaceOS::Meet` now implements the [`Powerable` interface](https://github.com/PlaceOS/driver/blob/master/src/placeos-driver/interface/powerable.cr) for system power.
- **(breaking)** `PlaceOS::Meet` now implements the [`Muteable` interface](https://github.com/PlaceOS/driver/blob/master/src/placeos-driver/interface/muteable.cr) for audio and video muting.
- Nicer error messages. When specifying an unknown input/output known refs are searched for a close match and suggested.
Changed:
- **(breaking)** Parameter order of `PlaceOS::Meet#volume` flipped to align with `mute` interfaces.
- Muting moved out of `PlaceOS::Router::Core` and into room logic.
Deprecated:
- `PlaceOS::Meet#powerup` - use `power(true)`
- `PlaceOS::Meet#shutdown` - use `power(false)`
Fixed:
- …
> Router / room logic

- drivers/cisco/meraki/meraki_locations.cr
There is an existing, optional regex filter for device operating system `regex_filter_device_os`, that applied only to the `locate_user` method.
This change uses the same filter and applies it to all exposed Locations (often rendered in apps as "device dots" from AreaManagement bindings).
A common use case is if staff have a particular managed device type of interest (e.g. Windows 10 laptops, or iPhones), and the enterprise only wants to LOCATE and COUNT (e.g. real-time device dots and retrospective analytics) those specific devices, then the device os regex filter setting can be set, and `AreaMangement` driver's `duplication_factor` should be set to `1.0`
> feat(meraki/locations): Apply device OS filter to list of Locations too

- docker-compose.yml
Update default driver test harness crystal version to 1.1.1
Tested briefly OK (ubuntu 20.04 in WSL2, Win10) with `./harness up` 
and compiled a driver that used Time `.step` (new in 1.1.0), which was not compiling in 1.0.0
> chore(harness): crystal 1.1.1 instead of 1.0.0

- drivers/gallagher/rest_api.cr
When the pdf is a binary, we are receiving an error from the driver.
> including fetching base64 pdf, some of them are coming as binary

- drivers/gallagher/rest_api.cr
forcing the response to be present if we want to return the object back. Gallagher api is returning a empty body but still successful response
> Gallagher update_cardholder being able to return nil as a good response

- drivers/vergesense/mqtt_export.cr
A simple logic driver that subscribes to changes in a neighboring Vergesense driver and publishes OCCUPANCY numbers for each space (desk/room/open-area) to a neighboring Generic MQTT driver.
The Vergesense floors to be considered must be configured as setting.
The MQTT base topic must be configured as setting.
The format of the MQTT Topic to publish to is static.
Tested OK e2e on placeos-dev server.
> feat(vergesense/mqtt_export): New VS > MQTT logic driver

- drivers/place/booking_approver.cr
a super simple logic driver that listens for new place Bookings and auto approves them (needed urgently).
Currently approves ALL of them.
can be improved later to selectively approve bookings of a certain type or zone or other condition
> feat(place): add booking_approver logic

- drivers/place/router/settings.cr
- drivers/place/router/settings_spec.cr
- drivers/place/router_spec.cr
Adds support for defining outputs not associated with a device (e.g. auxilaries in floor boxes).
> feat(place/router): support output aliases

- drivers/place/router.cr
- drivers/place/router_spec.cr
> feat(router): persist node status across reloads

- drivers/cisco/meraki/scanning_api.cr
On 3 of 3 meraki instances I have confirmed errors like: 
`Couldn't parse (Int32 | Nil) from \"153\" ... parsing Cisco::Meraki::Client#vlan`
```
module_name": "MerakiLocations",
"index": 1,
"message": "module raised: remote exception: Couldn't parse (Int32 | Nil) from \"153\" at line 1, column 508\n  parsing Cisco::Meraki::Client#vlan at line 1, column 501 (JSON::SerializableError) (PlaceOS::Driver::RemoteException) (PlaceOS::Driver::RemoteException)",
"backtrace": [
"/usr/share/crystal/src/json/serialization.cr:159:7 in 'initialize:__pull_for_json_serializable'",
"repositories/drivers/drivers/cisco/meraki/scanning_api.cr:103:5 in 'new_from_json_pull_parser'",
"repositories/drivers/drivers/cisco/meraki/scanning_api.cr:103:5 in 'new'",
"/usr/share/crystal/src/json/from_json.cr:153:11 in …
```
> fix(cisco/meraki): Client.vlan is now a String not Int32

- drivers/floorsense/models.cr
There is a typo not he property count, it should be Int32 with Capital I
> Fixing property type on Floorsense::UserGroup

- drivers/floorsense/models.cr
This PR adds some missing fields to the user model in floorsense.
> Add missing fields to the user model

- drivers/lenel/open_access.cr
- drivers/lenel/open_access/client.cr
- drivers/lenel/open_access/models.cr
- drivers/xy_sense/location_service_spec.cr
Been running this modified version in production fine for a year.
Additional features work fine:
- pagination of events
- card reader searching
- raw lookups
low level alarm related fields of reader were commented out as they will likely never be used. 
high level alarm fields remain as they may be used in the future.
There is an existing behaviour that still needs to be improved. On module start, it won't immediately go into online state. Need to manually force it to check_status before it will go Online.
> feat(lenel/openaccess): reader searching, raw lookup, event pagination

- drivers/cisco/ise/network_access.cr
- drivers/place/booking_notifier.cr
- drivers/place/event_mailer.cr
- drivers/place/visitor_mailer.cr
I was investigating an issue on a production deployment where I was running an older version of the ise driver which created users with their name as a random string instead of their email address. Due to the mismatch between the logic drivers and the ise service driver, 2 accounts were created for each user (with the same email address), one where name was a random string (created on the very first booking by a new ise user) and one where name=email (created in the subsequent booking).
This commit resolves the issue by always using the name field (which will contain the email) as the lookup.
It's also more efficient as the name field can directly access api objects, where as email requires a lookup (to get id or name), before an object can be updated or returned.
> fix(cisco/ise): reference user by name instead of email

- drivers/leviton/acquisuite.cr
- drivers/leviton/acquisuite_spec.cr
Simple update to the data format we save.
> fix(leviton): update data format

- drivers/place/survey_mailer.cr
- drivers/place/survey_mailer_spec.cr
Only send one email for each unique pair of `email + survey_id` per run, and mark all duplicates as sent.
> feat(survey): dedupe emails PPT-111

- docker-compose.yml
Update `docker-compose` file to use images which support multi-architecture.
**Benefits**
Developers running on AMD or ARM64 machines should be able to use images specific for their architecture.
None
> fix(docker-compose): update redis and install-shards image to multi-arch images tag

- drivers/leviton/acquisuite.cr
Pretty simple fix. I just forgot to load the config list out of settings when the driver starts/updates.
> fix(leviton): ensure config list is loaded from settings

- drivers/leviton/acquisuite.cr
Simply added the word "SUCCESS" or "FAILURE" to each body except the manifest request.
> fix(leviton): add SUCCESS to body of responses

- drivers/twenty_five_live_pro/api.cr
spcae_id parameter added to request body for list_events function.
**Benefits**
This will allow the api to filter api request based on space_id rather than locally filter events by searching for the space_id.
- fixes #
> Feat/25 live pro/space id body param

- drivers/place/bookings.cr
Some role based accounts running the Booking panel app (via api key) may not have MS Graph API delegated permissions to query the AAD user directory (e.g. PlaceOS local accounts).
This change allows those apps to query users via a driver exec instead of via a staff-api call. A corresponding frontend change would also be required.
> feat(placeos/room-events): add list_users func

- drivers/johnson_controls/metasys.cr
- drivers/johnson_controls/metasys_models.cr
Added content_type to headers for put request when send command is executed
per api documentation
**Benefits**
The api was failing before this quick fix
- fixes #
> Fix/johnson control/send command headers

- drivers/microsoft/graph_api_advanced.cr
- shard.yml
I chose to use the placeos/office365 lib instead of placeos/calendar (extend the existing graph api calendar driver), as it doesn't appear possible to use `@client.graph_request` when @client is placeos/calendar instead of placeos/office365. 
Is this the right track? Or is there a better approach.
This compiles but is untested.
> feat(microsoft/graph): new driver for direct ms graph api calls

- drivers/gobright/api.cr
- drivers/gobright/location_service.cr
Add support for GET spaces/state: 
https://t1b.gobright.cloud/swagger/index.html?url=/swagger/v1/swagger.json#/SpacesV2/SpacesV2_GetState
Mostly copied/pasted from existing GET spaces request (above it). Changed q param names only.
ALSO
Allow Gobright location services driver to specify a default spacetype for device_locations(). Just to workaround a new bug in GoBright API where no data is returned (instead of all) when no space type filter is specified.
> feat(gobright/api): add GET spaces/state request

- drivers/cisco/room_kit.cr
Edit cisco room kit comment so new build is triggered on updated build service
> chore(cisco): trigger room_kit build

- .github/workflows/ci.yml
upload-artifact and download-artifact @v3 are being deprecated
> chore(workflow): update artifact action version

- drivers/place/booking_notifier.cr
- drivers/place/visitor_mailer.cr
requres https://github.com/PlaceOS/staff-api/pull/337 for the signals to actually  be sent
> feat(visitor_mailer): [PPT-1430] notify on induction accepted/declined

- drivers/place/booking_approval_workflows.cr
> fix(place/booking_notifier): filter booking_type on event based actions

- drivers/place/auto_release.cr
- drivers/place/auto_release_spec.cr
add config options:
- skip_created_after_start: true
- skip_same_day: false
> feat(auto_release): [PPT-1835] skip_created_after_start and skip_same_day settings

- drivers/cisco/booking_panel_led_sync.cr
- drivers/cisco/booking_panel_led_sync_spec.cr
todo: 
- DONE: compile without errors, 
- spec
> Add logic driver to sync Cisco Webex Nagivator LED color to Bookings status via xAPI. Untested

- drivers/place/meet.cr
When the system is started, power on all devices listed in the `preview_outputs` setting.
This needs to be tested when joined and unjoined, before rolling out.
> feat(place/meet): power on preview_outputs on startup

- drivers/place/meet.cr
requires accompanying frontend change: https://github.com/PlaceOS/user-interfaces/commit/a9557b2651421a0321b56cb427833f2017c7192f`
When last deployed, this new feature caused an issue where no VC cameras would be listed by the UI.
This branch can be be used for e2e testing onsite, behaviour can be observed and then code changes made until it's confirmed working without new bugs.
> feat(place/meet): provide bindings for local camera lists

- drivers/epiphan/pearl.cr
- drivers/epiphan/pearl_models.cr
- drivers/epiphan/pearl_spec.cr
AI generated using:
```
I need a Recording driver for the Epiphan Pearl-2 and Pearl Mini. I believe they both share the same API
https://epiphan-video.github.io/pearl_api_swagger_ui/
These devices are connected to Epiphan Cloud
the key functions needed are Starting and stopping recordings programmatically
By leveraging this API, you can remotely control recordings – for example, starting and stopping lecture captures
The Pearl REST API provides endpoints to list “recorders” (recording channels) and control them. Each recording channel or recorder has an ID - these channels typically represent a room (one device may be shared between multiple physical meeting rooms / lecture spaces)
The Pearl API also allows control of live streaming in a similar manner (via …
```
> feat: add epiphan pearl driver
