- src/drivers/git_commands.cr
> fix(git_commands): correct redundant `to_s`

- Dockerfile
- shard.lock
- shard.yml
- spec/spec_helper.cr
- src/build.cr
- src/config.cr
- Bump crystal in Dockerfile to 0.35.0
- Update dependencies to `placeos` scoped versions
> build: support crystal 0.35.0

- docker-compose.yml
- shard.lock
- shard.yml
Set `CRYSTAL_PATH` environment variable in `docker-compose.yml`
Fixes #12
> fix: set local shards path

- Dockerfile
- shard.lock
- shard.yml
Bump shards and build against crystal 0.35.1
> build: crystal 0.35.1

- shard.lock
- src/config.cr
Super minor update to log both request entry and resolution on the test harness.
Added to provide some better user feedback when working on a driver that may include long-running tasks or chasing down an issue that’s causing execution to block.
> Request logging

- .github/workflows/crystal.yml
Add a github action that checks formatting with the crystal formatter and pipes to Ameba for linting.
Resolves #36.
> chore: add style action

- drivers/place/desk_bookings_locations.cr
- drivers/place/desk_bookings_locations_spec.cr
> Placeos desk bookings location service

- drivers/samsung/displays/mdc_protocol.cr
- drivers/samsung/displays/mdc_protocol_spec.cr
> fix(mdc): calculate correct checksums

- drivers/epson/projector/esc_vp21.cr
- drivers/epson/projector/esc_vp21_spec.cr
> Epson projector

- drivers/panasonic/display/protocol2.cr
- drivers/panasonic/display/protocol2_spec.cr
> Panasonic display

- drivers/global_cache/gc_100.cr
- drivers/global_cache/gc_100_spec.cr
Just going to open up an initial PR to get some feedback from you @KimBurgess when you can please. Not 100% sure what this device actually does but I think it's like a router/hub that you connect IO devices too I think?
> Global cache

- drivers/denon/amplifier/av_receiver.cr
- drivers/denon/amplifier/av_receiver_spec.cr
- drivers/mulesoft/models.cr
- drivers/qsc/q_sys_control.cr
- drivers/qsc/q_sys_control_spec.cr
- drivers/qsc/q_sys_remote.cr
- drivers/qsc/q_sys_remote_spec.cr
> Denon AV Receiver driver integration

- .travis.yml
- Dockerfile
- shard.lock
- shard.override.yml
- shard.yml
- src/report.cr
going to add a script for running driver specs as well
> bump to crystal 1.0.0

- drivers/sony/projector/pj_talk.cr
- drivers/sony/projector/pj_talk_spec.cr
I'll write more specs, just so consider this WIP for now
> feat(sony projector): add pj talk protocol

- shard.lock
- shard.yml
Fixes an issue with symbol resolution in the spec runner
> build: bump to placeos-driver 5.0.8

- drivers/place/mqtt.cr
- drivers/place/mqtt_spec.cr
- drivers/place/mqtt_transport_adaptor.cr
- shard.lock
- shard.yml
allows for a single connection to be used for multiple drivers
once configured, various drivers can subscribe to interested state via typical PlaceOS subscription model
> feat: add generic MQTT driver

- drivers/echo360/device_capture.cr
- drivers/echo360/device_capture_spec.cr
- shard.lock
- shard.yml
was actually quite challenging to migrate in the end
XML is not fun to parse so I cheated
> feat: add echo360 driver

- drivers/biamp/nexia.cr
- drivers/biamp/tesira.cr
- drivers/global_cache/gc_100.cr
- drivers/nec/display.cr
to test if disconnect is not being called
> fix: clear schedules on connect

- .ameba.yml
- drivers/mulesoft/calendar_exporter.cr
- Tiny fixes for lints.
- Adds a ignore rule for `repositories`, which are external to PlaceOS/drivers
I have not addressed the comments raised in https://github.com/PlaceOS/drivers/commit/d97bb43f96ce9fc7a5cff2f174f597024e026d07 as I believe they should be checked by the implementer first.
> lint(mulesoft): fix ameba lints

- drivers/cisco/ise/guests.cr
Sorry about this, I didn't run `crystal tool format` for these files so I think that is why some of the CI tests are failing
> chore(ise): run crystal tool format

- drivers/gallagher/rest_api.cr
- drivers/gallagher/rest_api_models.cr
- drivers/gallagher/rest_api_spec.cr
> Gallagher rest api

- harness
Clarify and tidy some of the output of `harness`
> docs: clearer `harness` output

- drivers/aws/sns_sms.cr
- drivers/lenel/open_access.cr
- drivers/lenel/open_access/client.cr
- drivers/lenel/open_access_spec.cr
- shard.lock
`before_request` was referencing the definition introduced in this [commit](https://github.com/PlaceOS/driver/commit/d416e53cb9de49d4e5916bfc889567ae5d2c7c72#diff-933bebc00e20ad0f8e3b3aad8fd2b5ce20fccd576e8ab27ba823f8109961c6f9)
Closes #191
> fix: change conflicting method name

- drivers/office_rnd/office_rnd_api.cr
- drivers/office_rnd/office_rnd_api_spec.cr
> fix(officernd): refactor request functions

- .github/workflows/ci.yml
Keep other pipelines running even if one fails
> ci: disable fail fast

- .github/workflows/ci.yml
Adds crystal v1.1.1 to the ci matrix
> ci: add crystal 1.1.1 to matrix

- drivers/place/meet.cr
- drivers/place/meet_spec.cr
Base implementation of `meet` style room.
Extends from the core signal router in #209.
> Meeting room logic

- drivers/cisco/meraki/dashboard.cr
- drivers/cisco/meraki/meraki_locations.cr
- drivers/cisco/meraki/meraki_locations_spec.cr
- drivers/cisco/meraki/scanning_api.cr
> feat(cisco meraki): add mv sense sensor data

- drivers/floorsense/custom_bookings_sync.cr
- drivers/floorsense/models.cr
and there is potentially a difference in desk IDs between the platforms
> feat(floorsense booking sync): where users already exist

- drivers/place/bookings.cr
when a change event occurs
fixes #231
> feat(place bookings): add a configurable delay before syncing

- drivers/lenel/open_access.cr
- drivers/lenel/open_access/client.cr
- drivers/lenel/open_access/models.cr
- Support querying logged events that match a given filter
- Support querying logged events within a given Time range, that match a given filter
- tidy up timezones implemention
> Lenel Openaccess: Support querying Logged Events

- drivers/vergesense/mqtt_export.cr
This reverts commit 5d9a27031720a22e2792c3049c54773820687da8.
> Revert "fix(vergesense/mqttt_export): remove root topic (#271)"

- drivers/floorsense/desks.cr
- drivers/floorsense/desks_websocket.cr
Guy we need to add active booking because when you are arriving early to the desk, confirm booking fails.
But using active booking endpoint allows to use the desk!
> adding desk_scan and activate booking into floorsense driver

- drivers/crestron/cres_next.cr
- drivers/crestron/nvx_address_manager.cr
- drivers/crestron/nvx_address_manager_spec.cr
- drivers/crestron/nvx_models.cr
- drivers/crestron/nvx_rx.cr
- drivers/crestron/nvx_rx_models.cr
- drivers/crestron/nvx_rx_spec.cr
- drivers/crestron/nvx_scaler_control.cr
- drivers/crestron/nvx_scaler_control_spec.cr
- drivers/crestron/nvx_tx.cr
- drivers/crestron/nvx_tx_spec.cr
> feat: add crestron nvx drivers

- drivers/rhombus/integration_details.md
- drivers/rhombus/security_interop.cr
- drivers/rhombus/security_interop_models.cr
- drivers/rhombus/security_interop_spec.cr
- drivers/rhombus/security_mock.cr
- shard.lock
- shard.yml
bridging rhombus with on site security systems
> feat: add rhombus security interop

- drivers/place/staff_api.cr
Considering the new API, we are adding the new parameter for booking creation.
> adding utm source parameter for bookings

- drivers/floorsense/models.cr
Hi guys, last week I added these fields, but there is a bug, pin is a string.
> Fix: user pin string

- drivers/floorsense/desks.cr
Hi guys, this PR adds a limit/offset to the user_list method in floorsense.
Can I have a review plese?
> Limit offset user list

- drivers/place/staff_api.cr
- shard.lock
Once approved the method merge for metadata, we can include it into staff api driver 
- https://github.com/PlaceOS/crystal-client/pull/30
> feat(staff-api): add merge metadata method

- drivers/place/staff_api.cr
> adding signal method to staff_api

- drivers/place/staff_api.cr
Currently search and user creation is returning nil for any case.
> create user and query user they must have a return

- drivers/lutron/quantum.cr
- shard.lock
- shard.yml
Added a Lutron Quantum driver.
**Benefits**
Ability to control Quantum devices.
A bug might occur.
- Closes #320
> Add Quantum driver

- drivers/place/booking_notifier.cr
> fix(place/booking_notifier): action created bookings

- drivers/stripe/api.cr
- shard.lock
- shard.yml
> Add Stripe driver

- shard.lock
- fix get Scenes
- add get area
- add get zones
- Change security level of SET commands to Support (set level, set scene)
> Quantum changes

- drivers/crestron/fusion.cr
- drivers/siemens/desigo.cr
- shard.lock
- shard.yml
Issues with driver shards failing to introspect generics.
Updated the last argument of the execute function to take JSON string.
> Add Siemens Desigo driver

- drivers/infosilem/campus.cr
- drivers/infosilem/models.cr
- drivers/infosilem/room_schedule.cr
- drivers/rhb_access/axiom_room_logic.cr
- shard.lock
- shard.yml
Added the Infosilem Campus driver to extract room bookings.
**Benefits**
Driver for the Infosilem Campus.
None.
Additional functions might be required to actually filter bookings by multiple different arguments.
> Added Infosilem Campus driver

- drivers/crestron/fusion.cr
Crestron Fusion methods for possible future use.
> feat(crestron): room methods

- drivers/leviton/acquisuite.cr
Super simple. Can someone approve asap, thanks.
> chore(leviton): add debugging to acquisuite driver

- drivers/leviton/acquisuite.cr
Just a few little logic updates based on real world testing.
> fix(leviton): small webhook fixes

- drivers/gallagher/rest_api.cr
- drivers/gallagher/rest_api_models.cr
- drivers/gallagher/rest_api_spec.cr
allows Rhombus integration to function
> feat(gallagher\rest_api): implement DoorSecurity interface

- drivers/leviton/acquisuite.cr
Just a small change to the debugging in the Leviton driver.
> chore(leviton): Set debugging to info level to persist in logs

- drivers/cisco/meraki/dashboard.cr
- drivers/cisco/meraki/meraki_locations.cr
- drivers/cisco/meraki/meraki_locations_spec.cr
- drivers/cisco/meraki/scanning_api.cr
currently missing the requests to obtain the port status with the mac addresses
> feat(cisco/meraki): add support for wired desk tracking

- drivers/place/booking_notifier.cr
polling now optional
fix unneeded wifi cred generation.
> fix(placeos/booking_notifier): optional polling . rm unneeded wifi cred generation.

- drivers/place/visitor_mailer.cr
Add templates for guest events
```cr
event_template:    "event",
booking_template:  "booking",
```
> feat(visitor_mailer): multiple templates

- drivers/leviton/acquisuite.cr
- drivers/leviton/acquisuite_spec.cr
Little change to make sure data is actually saved.
> fix(leviton): ensure right file is unzipped

- drivers/place/staff_api.cr
- drivers/place/visitor_mailer.cr
adds a new field for use in templates:
- `event_time`, shows `all day` for all day bookings and `event_start` for other bookings
> feat(visitor_mailor): all day event time PPT-107

- drivers/cisco/ise/network_access.cr
- drivers/cisco/webex/instant_connect.cr
- drivers/leviton/acquisuite.cr
- drivers/place/booking_notifier.cr
- drivers/place/chat/health_rooms.cr
- drivers/place/event_mailer.cr
- drivers/place/password_generator_helper.cr
- drivers/place/visitor_mailer.cr
Adds a configurable password generator to:
- place/booking_notifier
- place/event_mailer
- place/visitor_mailer
- cisco/ice/network_access
with the following defaults:
```cr
DEFAULT_PASSWORD_LENGTH            = 6
DEFAULT_PASSWORD_EXCLUDE           = "0Oo1Il`'\\/"
DEFAULT_PASSWORD_MINIMUM_LOWERCASE = 1
DEFAULT_PASSWORD_MINIMUM_UPPERCASE = 0
DEFAULT_PASSWORD_MINIMUM_NUMBERS   = 1
DEFAULT_PASSWORD_MINIMUM_SYMBOLS   = 0
```
> feat(password_generator): [PPT-90] add configurable password generator

- drivers/leviton/acquisuite.cr
Little one to fix the ASHRAE issues.
> fix(levtion): allow for null values in readings

- drivers/leviton/acquisuite.cr
> fix(leviton): Allow for readings to use the correct datatype

- drivers/lenel/open_access.cr
Add 1 new func to return the list of all cardholders that have a given email address (instead of just the first result).
> feat(lenel/openaccess): add lookup_cardholderS : []

- drivers/vecos/releezme.cr
The auth api changes depending on dev/stg/prod environments, so needs to be a setting not a hardcoded string
> fix(releezme/api): auth domain is a setting not hardcoded

- drivers/global_cache/projector_screen.cr
- drivers/global_cache/projector_screen_spec.cr
enable meeting room control logic driver to control projector screens via globalcache (not just IP modules
> feat(globalcache): Add projector screen logic driver

- drivers/place/event_setup_breakdown_time.cr
- add attendees
- skip if no changes
> fix(event_setup_breakdown_time): add attendees to setup/breakdown events

- drivers/place/attendee_scanner.cr
- drivers/place/staff_api.cr
Create a driver that is able to
https://acaprojects.atlassian.net/browse/PPT-1348
> feat(PPT-1348): Add functionality to fetch list of guests

- drivers/floorsense/desks_websocket.cr
https://acaprojects.atlassian.net/browse/SD-5653
> fix(floorsense/desk_list): handle controllers lacking desk api

- drivers/place/auto_release.cr
- drivers/place/auto_release_spec.cr
- drivers/place/booking_model.cr
adds:
- `unique_templates`
- `default_work_preferences`
- `release_outside_hours`
- `all_day_start`
- per resource custom `time_before`/`time_after`
> feat(auto_release): [PPT-1903|PPT-1901|PPT-1900|MT-346] more settings

- drivers/shure/intellimix_room.cr
- drivers/shure/intellimix_room_spec.cr
Created files:
- drivers/shure/intellimix_room.cr - Main driver implementation
- drivers/shure/intellimix_room_spec.cr - Comprehensive test suite
Key Features Implemented:
🔧 Core Mixer Functionality:
- Input/output gain control (-100.0 to 20.0 dB range)
- Input/output mute controls
- Master gain and master mute
- Channel-specific controls (1-8 channels configurable)
🎛️ Audio Processing:
- Noise reduction control per channel
- Automatic gain control (AGC) per channel
- Audio level monitoring for inputs and outputs
📡 Communication:
- TCP connection on port 2244
- Shure command string protocol (< command > format)
- Proper response parsing and status tracking
- Error handling and validation
🔌 Interface Compliance:
- Implements Interface::AudioMuteable for standard mute functionality
- …
> feat(shure/intellimix): added new driver
